services:

    firebase_cloud_messaging:
        class: Ibtikar\GoogleServicesBundle\Service\FirebaseCloudMessaging
        arguments: [ '%ibtikar_google_services.firebase_api_key%', '@logger' ]
        tags:
             - { name: monolog.logger, channel: firebase_notifications }

    google_shorten_url:
        class: Ibtikar\GoogleServicesBundle\Service\ShortenUrl
        arguments: [ '%ibtikar_google_services.shorten_url_key%' ]

    firebase:
        class: Ibtikar\GoogleServicesBundle\Service\FireBaseHandler
        arguments: [ '%ibtikar_google_services.firebase_url_base%', '%ibtikar_google_services.firebase_database_secret%' ]

    firebase_database:
        class: Ibtikar\GoogleServicesBundle\Service\FireBaseRetrievingData
        arguments: ['%ibtikar_google_services.firebase_credentials_path%' ]

    google.distancematrix:
        class: Ibtikar\GoogleServicesBundle\Service\GoogleDistanceMatrix
        arguments: [ '%ibtikar_google_services.google_distance_matrix_url_base%','%ibtikar_google_services.google_distance_matrix_key%' ]

    google.directions:
        class: Ibtikar\GoogleServicesBundle\Service\GoogleDirections
        arguments: [ '%ibtikar_google_services.google_directions_url_base%','%ibtikar_google_services.google_directions_key%' ]
